import type { ReportPeriod } from "@prisma/client";
import { Document, Page, StyleSheet, Text, View } from "@react-pdf/renderer";

const styles = StyleSheet.create({
  page: {
    padding: 32,
    fontSize: 11,
    color: "#0f172a",
    fontFamily: "Helvetica",
    backgroundColor: "#f8fafc",
  },
  section: {
    marginBottom: 18,
    padding: 16,
    borderRadius: 12,
    backgroundColor: "#ffffff",
  },
  row: {
    flexDirection: "row",
    gap: 12,
  },
  metric: {
    flex: 1,
    padding: 12,
    borderRadius: 10,
    backgroundColor: "#f1f5f9",
  },
  heading: {
    fontSize: 20,
    marginBottom: 6,
    fontWeight: 700,
  },
  subheading: {
    fontSize: 12,
    color: "#475569",
    marginBottom: 12,
  },
  label: {
    fontSize: 9,
    color: "#64748b",
    marginBottom: 4,
    textTransform: "uppercase",
  },
  value: {
    fontSize: 16,
    fontWeight: 700,
  },
  listItem: {
    marginBottom: 8,
    lineHeight: 1.4,
  },
});

export function ReportPdf({
  title,
  period,
  summary,
}: {
  title: string;
  period: ReportPeriod;
  summary: {
    monthlyIncome: number;
    monthlyExpenses: number;
    net: number;
    financialScore: number;
    categoryBreakdown?: Array<{ label: string; value: number }>;
    insights?: Array<{ title: string; body: string }>;
  };
}) {
  return (
    <Document>
      <Page size="A4" style={styles.page}>
        <View style={styles.section}>
          <Text style={styles.heading}>{title}</Text>
          <Text style={styles.subheading}>
            {period} financial intelligence report generated by PesaPilot AI
          </Text>
        </View>

        <View style={[styles.section, styles.row]}>
          <View style={styles.metric}>
            <Text style={styles.label}>Income</Text>
            <Text style={styles.value}>
              KES {Math.round(summary.monthlyIncome).toLocaleString()}
            </Text>
          </View>
          <View style={styles.metric}>
            <Text style={styles.label}>Expenses</Text>
            <Text style={styles.value}>
              KES {Math.round(summary.monthlyExpenses).toLocaleString()}
            </Text>
          </View>
          <View style={styles.metric}>
            <Text style={styles.label}>Net</Text>
            <Text style={styles.value}>KES {Math.round(summary.net).toLocaleString()}</Text>
          </View>
          <View style={styles.metric}>
            <Text style={styles.label}>Score</Text>
            <Text style={styles.value}>{summary.financialScore}/100</Text>
          </View>
        </View>

        <View style={styles.section}>
          <Text style={styles.heading}>Category Mix</Text>
          {(summary.categoryBreakdown ?? []).slice(0, 6).map((entry) => (
            <Text key={entry.label} style={styles.listItem}>
              {entry.label}: KES {Math.round(entry.value).toLocaleString()}
            </Text>
          ))}
        </View>

        <View style={styles.section}>
          <Text style={styles.heading}>AI Insights</Text>
          {(summary.insights ?? []).slice(0, 5).map((insight) => (
            <View key={insight.title} style={{ marginBottom: 10 }}>
              <Text style={{ fontWeight: 700, marginBottom: 3 }}>{insight.title}</Text>
              <Text style={{ lineHeight: 1.5 }}>{insight.body}</Text>
            </View>
          ))}
        </View>
      </Page>
    </Document>
  );
}
